apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # MinIO Creds (admin / password123)
  minio-user: YWRtaW4=
  minio-pass: cGFzc3dvcmQxMjM=
  
  # Postgres Creds (user / password / crypto_db)
  pg-user: dXNlcg==
  pg-pass: cGFzc3dvcmQ=
  pg-db: Y3J5cHRvX2Ri
  google-api-key: QUl6YVN5Q2ZtTGZOdHJKRUhOVWN3aUhEdXVvZU04TnduQjFONmdN